name: your_app_name
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  # localization language
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  # network Service
  http: ^0.13.4
  # to pick Image
  image_picker: ^0.8.5+3
  #show image and Cached 
  cached_network_image: ^3.2.0
  #state managment
  provider: ^6.0.3
  # google font style 
  google_fonts: ^3.0.1
  #local database
  shared_preferences: ^2.0.15
  #firebase use
  firebase_storage:
  firebase_core: ^1.14.1
  cloud_firestore:
  firebase_auth: ^3.3.14
  #videos and Audio
  video_player: ^2.4.5
  audioplayers: ^1.0.1
  record: ^4.1.1
  # pick time 
  date_time_picker: ^2.1.0
  #pick country code 
  country_code_picker: ^2.0.2
  #permission_handler
  permission_handler: ^10.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.1.10

flutter:
  generate: true

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300